version: '3.8'
services:
  backend:
    build:
      context: "./tp/61033 - Quiroga, José María/tp6/backend"
    ports:
      - "8000:8000"
    volumes:
      - "./tp/61033 - Quiroga, José María/tp6/backend:/app"
  frontend:
    build:
      context: "./tp/61033 - Quiroga, José María/tp6/frontend/next-app"
    ports:
      - "3000:3000"
    depends_on:
      - backend
