[project]
name = "tp6-backend"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
  "fastapi>=0.115",
  "uvicorn[standard]>=0.30",
  "sqlmodel>=0.0.22",
  "passlib[bcrypt]>=1.7",
  "python-jose[cryptography]>=3.3",
  "pydantic[email]>=2.7"
]
